apiVersion: v2
name: auth
description: Helm chart for deploying Prakarsa Auth Service
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Prakarsa Team
    email: prakarsaapp@gmail.com
keywords:
  - prakarsa
  - auth