definitions:
  request.CompleteProfileReq:
    properties:
      birth_date:
        type: string
      gender:
        type: string
      institution_id:
        type: string
    type: object
  request.SignInReq:
    properties:
      email:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    type: object
  request.SignUpReq:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  termsOfService: http://swagger.io/terms/
  title: Auth API
  version: 1.0.4
paths:
  /api/v1/auth/complete-profile:
    post:
      consumes:
      - application/json
      description: CompleteProfile
      parameters:
      - description: User ID from Gateway
        in: header
        name: x-user-id
        required: true
        type: string
      - description: CompleteProfile user
        in: body
        name: completeprofile
        required: true
        schema:
          $ref: '#/definitions/request.CompleteProfileReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: CompleteProfile
      tags:
      - Auth
  /api/v1/auth/profile-completion:
    get:
      consumes:
      - application/json
      description: ProfileCompletion
      parameters:
      - description: User ID from Gateway
        in: header
        name: x-user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ProfileCompletion
      tags:
      - Auth
  /api/v1/auth/signin:
    post:
      consumes:
      - application/json
      description: SignIn
      parameters:
      - description: SignIn user
        in: body
        name: signin
        required: true
        schema:
          $ref: '#/definitions/request.SignInReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: SignIn
      tags:
      - Auth
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: SignUp
      parameters:
      - description: SignUp user
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/request.SignUpReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: SignUp
      tags:
      - Auth
  /api/v1/auth/update-profile:
    put:
      consumes:
      - multipart/form-data
      description: UpdateProfile
      parameters:
      - description: User ID from Gateway
        in: header
        name: x-user-id
        required: true
        type: string
      - description: Name
        in: formData
        name: name
        type: string
      - description: Avatar file
        in: formData
        name: avatar
        type: file
      - description: Gender
        in: formData
        name: gender
        type: string
      - description: Birth Date
        in: formData
        name: birth_date
        type: string
      - description: Slug Name
        in: formData
        name: slug_name
        type: string
      - description: About Me
        in: formData
        name: about_me
        type: string
      - description: Institution ID
        in: formData
        name: institution_id
        type: string
      - description: Linkedin URL
        in: formData
        name: linkedin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: UpdateProfile
      tags:
      - Auth
  /api/v1/auth/user-profile:
    get:
      consumes:
      - application/json
      description: UserProfile
      parameters:
      - description: User ID from Gateway
        in: header
        name: x-user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: UserProfile
      tags:
      - Auth
securityDefinitions:
  JwtToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
